# A.I.D.A. Registry Integration Configuration
# Machine-readable configuration for React Bits and TweakCn integration

metadata:
  created: "2025-09-25"
  last_updated: "2025-09-25"
  version: "1.0.0"
  description: "Registry integration strategy and implementation guide"
  source_file: "REGISTRY_INTEGRATION_GUIDE.md"

registry_configuration:
  components_json:
    description: "Registry configuration in components.json"
    structure:
      registries:
        - name: "shadcn"
          url: "https://ui.shadcn.com/registry"
          priority: "primary"
          description: "Official shadcn/ui components"
        - name: "react-bits"
          url: "https://reactbits.dev"
          priority: "secondary"
          useFor: ["landing-page", "animations", "interactive-components"]
          description: "Animated, interactive & fully customizable React components"
        - name: "tweakcn"
          url: "https://tweakcn.com"
          priority: "secondary"
          useFor: ["theming", "voice-orb-states", "empathy-bar-colors"]
          description: "Powerful Theme Editor for shadcn/ui"

component_integration:
  voice_orb:
    name: "Voice Orb Enhancement"
    description: "Enhanced voice interface with animations and theming"
    base_component: "shadcn/ui Button"
    animations: "react-bits ParticleBackground"
    theming: "tweakcn useTheme hook"
    states:
      idle:
        color: "theme.colors.voice.idle"
        description: "Calm blue glow - ready for voice commands"
        animation: "Gentle pulsing"
      listening:
        color: "theme.colors.voice.listening"
        description: "Purple light - processing voice input"
        animation: "Active pulsing + ParticleBackground"
      success:
        color: "theme.colors.voice.success"
        description: "Steady green - task completed"
        animation: "Confirmation pulse"
    implementation:
      imports:
        - "import { Button } from '@/components/ui/button'"
        - "import { ParticleBackground } from 'react-bits'"
        - "import { useTheme } from 'tweakcn'"
      key_features:
        - "Dynamic color states based on voice status"
        - "Particle effects during listening state"
        - "Accessibility compliance with ShadCN base"
        - "Smooth transitions between states"

  empathy_bar:
    name: "Empathy Bar Implementation"
    description: "Real-time emotional state visualization"
    base_component: "shadcn/ui Progress"
    animations: "framer-motion (via react-bits)"
    theming: "tweakcn dynamic colors"
    emotional_states:
      calm:
        color: "theme.colors.empathy.calm"
        description: "Normal, relaxed teacher state"
        threshold: "stressLevel <= 0.7"
      stress:
        color: "theme.colors.empathy.stress"
        description: "AI detects frustration or stress"
        threshold: "stressLevel > 0.7"
    implementation:
      imports:
        - "import { Progress } from '@/components/ui/progress'"
        - "import { useTheme } from 'tweakcn'"
        - "import { AnimatePresence, motion } from 'framer-motion'"
      key_features:
        - "Real-time color changes based on voice analysis"
        - "Smooth transitions with motion.div"
        - "Progress bar shows stress level percentage"
        - "Accessibility with ShadCN base component"

  landing_page_hero:
    name: "Landing Page Hero Section"
    description: "Interactive hero with particle system and Voice Orb"
    base_components: "shadcn/ui Button"
    animations: "react-bits ParticleSystem, FloatingElements"
    theming: "tweakcn color palette"
    layout:
      structure: "Full-screen section with centered Voice Orb"
      particle_system:
        particles: 100
        color: "theme.colors.primary.purple"
        intensity: 0.8
        position: "absolute inset-0"
      floating_elements:
        - text: "Ask Anything"
          position: "top"
        - text: "Get Instant Insight"
          position: "right"
        - text: "Your District, Your Data"
          position: "left"
    implementation:
      imports:
        - "import { Button } from '@/components/ui/button'"
        - "import { ParticleSystem, FloatingElements } from 'react-bits'"
        - "import { useTheme } from 'tweakcn'"
      key_features:
        - "Mesmerizing particle system background"
        - "Voice Orb at center with floating elements"
        - "Responsive design for all screen sizes"
        - "CTA button with theme colors"

migration_plan:
  phase_1_foundation:
    name: "Foundation Setup"
    duration: "Week 1"
    tasks:
      - "Install React Bits and TweakCn packages"
      - "Set up theme configuration"
      - "Create base component wrappers"
      - "Configure registry in components.json"
    deliverables:
      - "Working registry configuration"
      - "Basic theme system"
      - "Component wrapper templates"

  phase_2_voice_interface:
    name: "Voice Interface Enhancement"
    duration: "Week 1-2"
    tasks:
      - "Enhance VoiceInterface.tsx with animations"
      - "Add Empathy Bar component"
      - "Implement dynamic theming"
      - "Test voice recognition with animations"
    deliverables:
      - "Enhanced Voice Orb with states"
      - "Working Empathy Bar"
      - "Dynamic theme switching"

  phase_3_landing_page:
    name: "Landing Page Development"
    duration: "Week 2"
    tasks:
      - "Create hero section with particle system"
      - "Build interactive feature showcase"
      - "Implement responsive animations"
      - "Optimize for mobile performance"
    deliverables:
      - "Stunning hero section"
      - "Interactive feature showcase"
      - "Mobile-optimized animations"

  phase_4_dashboard:
    name: "Dashboard Enhancement"
    duration: "Week 3"
    tasks:
      - "Add subtle animations to existing widgets"
      - "Implement emotional responsiveness"
      - "Optimize performance"
      - "Test accessibility compliance"
    deliverables:
      - "Enhanced dashboard widgets"
      - "Emotional responsiveness"
      - "Performance optimizations"

performance_requirements:
  bundle_size:
    shadcn_ui: "~50KB"
    react_bits: "~30KB"
    tweakcn: "~20KB"
    total_addition: "~100KB"
    target: "<100KB additional"
  
  animation_performance:
    target_fps: ">60fps"
    optimization_strategies:
      - "Use will-change CSS property for animated elements"
      - "Implement requestAnimationFrame for smooth transitions"
      - "Lazy load heavy animations"
      - "Test on mobile devices for voice interface"
  
  voice_interface_optimization:
    requirements:
      - "Animations don't interfere with voice recognition"
      - "Particle effects subtle during voice interactions"
      - "Use CSS transforms instead of layout changes"
      - "Implement reduced motion preferences"
    testing:
      - "Test voice recognition accuracy with animations"
      - "Verify mobile touch interactions"
      - "Check screen reader compatibility"

accessibility_compliance:
  wcag_standards:
    level: "WCAG 2.1 AA"
    requirements:
      - "All animations respect prefers-reduced-motion"
      - "Color changes maintain 4.5:1 contrast ratio"
      - "Voice Orb remains keyboard accessible"
      - "Screen reader announcements for state changes"
  
  voice_interface_accessibility:
    requirements:
      - "Clear focus indicators for voice controls"
      - "Audio feedback for state changes"
      - "Fallback options for animation failures"
      - "Consistent interaction patterns"
    testing:
      - "Screen reader compatibility"
      - "Keyboard navigation"
      - "Voice recognition accuracy"

testing_strategy:
  component_testing:
    scope: "Test each registry integration separately"
    checks:
      - "Verify ShadCN accessibility features remain intact"
      - "Check animation performance on various devices"
      - "Validate theme switching functionality"
      - "Test component isolation"
  
  voice_interface_testing:
    scope: "Ensure animations don't affect voice functionality"
    checks:
      - "Voice recognition accuracy with animations"
      - "Screen reader compatibility"
      - "Keyboard navigation"
      - "Mobile touch interactions"
      - "Performance impact on voice processing"
  
  integration_testing:
    scope: "Test all three registries working together"
    checks:
      - "No CSS conflicts between registries"
      - "Bundle size impact within limits"
      - "Build process validation"
      - "Cross-browser compatibility"

success_metrics:
  technical:
    bundle_size_increase: "<100KB"
    animation_performance: ">60fps"
    voice_interface_response_time: "<2s"
    accessibility_score: ">90"
    lighthouse_mobile_score: ">90"
  
  user_experience:
    visual_appeal: "Enhanced with animations"
    interaction_flows: "Smooth and intuitive"
    emotional_responsiveness: "Real-time adaptation"
    professional_polish: "Hackathon-ready presentation"

implementation_timeline:
  week_1:
    focus: "Setup & Voice Orb"
    tasks:
      - "Configure registries"
      - "Enhance VoiceInterface component"
      - "Implement basic theming"
    deliverables:
      - "Working registry setup"
      - "Enhanced Voice Orb"
      - "Basic theme system"

  week_2:
    focus: "Landing Page"
    tasks:
      - "Create hero section"
      - "Build particle system"
      - "Implement feature showcase"
    deliverables:
      - "Stunning landing page"
      - "Interactive hero section"
      - "Feature showcase"

  week_3:
    focus: "Dashboard & Polish"
    tasks:
      - "Enhance existing components"
      - "Add emotional responsiveness"
      - "Performance optimization"
    deliverables:
      - "Enhanced dashboard"
      - "Emotional responsiveness"
      - "Performance optimizations"

  week_4:
    focus: "Testing & Refinement"
    tasks:
      - "Comprehensive testing"
      - "Accessibility validation"
      - "Final polish for hackathon"
    deliverables:
      - "Fully tested system"
      - "Accessibility compliance"
      - "Hackathon-ready demo"

code_examples:
  voice_orb_enhancement:
    description: "Enhanced Voice Orb with React Bits animations and TweakCn theming"
    file: "src/components/VoiceOrb.tsx"
    imports:
      - "import { Button } from '@/components/ui/button'"
      - "import { ParticleBackground } from 'react-bits'"
      - "import { useTheme } from 'tweakcn'"
    key_functions:
      - "getOrbStyles() - Dynamic color based on state"
      - "ParticleBackground - Animation during listening"
      - "useTheme() - TweakCn theming integration"
  
  empathy_bar_implementation:
    description: "Empathy Bar with emotional state theming"
    file: "src/components/EmpathyBar.tsx"
    imports:
      - "import { Progress } from '@/components/ui/progress'"
      - "import { useTheme } from 'tweakcn'"
      - "import { AnimatePresence, motion } from 'framer-motion'"
    key_functions:
      - "getBarColor() - Dynamic color based on stress level"
      - "motion.div - Smooth color transitions"
      - "Progress - ShadCN base component"
  
  landing_page_hero:
    description: "Hero section with particle system and Voice Orb"
    file: "src/components/HeroSection.tsx"
    imports:
      - "import { Button } from '@/components/ui/button'"
      - "import { ParticleSystem, FloatingElements } from 'react-bits'"
      - "import { useTheme } from 'tweakcn'"
    key_functions:
      - "ParticleSystem - Background animation"
      - "FloatingElements - Interactive text elements"
      - "VoiceOrb - Central interactive element"

integration_benefits:
  development:
    - "Maintains existing ShadCN/UI foundation"
    - "Layers React Bits animations for enhancement"
    - "Uses TweakCn for dynamic theming"
    - "Ensures accessibility compliance"
    - "Optimizes for voice interface performance"
  
  user_experience:
    - "Stunning visual appeal for hackathon judges"
    - "Smooth, professional interactions"
    - "Emotional responsiveness and intelligence"
    - "Mobile-first voice experience"
    - "Accessible to all users"
  
  technical:
    - "Minimal bundle size impact (~100KB)"
    - "High performance animations (>60fps)"
    - "Voice interface compatibility"
    - "Cross-browser support"
    - "Easy maintenance and updates"
